"""add scan_history table

Revision ID: 3598599c8c0d
Revises: 5819cc17f09f
Create Date: 2026-06-07 22:59:32.190191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3598599c8c0d'
down_revision = '5819cc17f09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))

    op.drop_table('scan_history')
    # ### end Alembic commands ###
