"""add email verification to users

Revision ID: 5819cc17f09f
Revises: a8e2d5f31b7c
Create Date: 2026-06-07 21:51:24.246012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5819cc17f09f'
down_revision = 'a8e2d5f31b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verify_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
