"""remove gemini_api_key from users

Revision ID: 74a286e65b49
Revises: f76103287e11
Create Date: 2026-06-07 11:18:54.058166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a286e65b49'
down_revision = 'f76103287e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gemini_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_api_key', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
