"""add ai quota fields and cover note cache

Revision ID: 75ee9f96c50e
Revises: 836150733ad9
Create Date: 2026-06-09 17:22:30.640317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ee9f96c50e'
down_revision = '836150733ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_note', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_calls_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_calls_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ai_calls_reset_date')
        batch_op.drop_column('ai_calls_today')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('cover_note')

    # ### end Alembic commands ###
