"""add is_admin to users

Revision ID: 836150733ad9
Revises: 3598599c8c0d
Create Date: 2026-06-08 00:00:30.317803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836150733ad9'
down_revision = '3598599c8c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
