"""add daily scan limit tracking to user_settings

Revision ID: f76103287e11
Revises: bbb12c5f8de4
Create Date: 2026-06-07 18:30:42.863838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76103287e11'
down_revision = 'bbb12c5f8de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_scan_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_scan_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('last_scan_date')
        batch_op.drop_column('daily_scan_count')

    # ### end Alembic commands ###
